const GET_OTP_CONSTANTS = {
  ADD_NUMBER: "ADD_NUMBER",
  GET_OTP_INIT: "GET_OTP_INIT",
  GET_OTP_SUCCESS: "GET_OTP_SUCCESS",
  GET_OTP_ERROR: "GET_OTP_ERROR"
}

const VERIFY_OTP_CONSTANTS = {
  VERIFY_OTP_INIT: "VERIFY_OTP_INIT",
  VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_ERROR: "VERIFY_OTP_ERROR"
}

const BOTTOM_TAB = {
  TAB_CHANGE: "TAB_CHANGE"
}

export {
  GET_OTP_CONSTANTS,
  VERIFY_OTP_CONSTANTS,
  BOTTOM_TAB
}